version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - .:/myapp
    environment:
      RAILS_ENV: development
      DB_USER: &db_user postgres
      DB_PASSWORD: &db_password postgres
    links:
      - db
    stdin_open: true

  # PostSQL
  db:
    image: postgres:11.2
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgresql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: *db_user
      POSTGRES_PASSWORD: *db_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

  # MySQL
  # db:
  #   image: mysql:5.7
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
  #     - ./docker/mysql/conf.d:/etc/mysql/conf.d
  #     - ./docker/mysql/data:/var/lib/mysql
  #     - ./docker/mysql/log:/var/log/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_USER: *db_user
  #     MYSQL_PASSWORD: *db_password
